version: '3'
services:
  web:
    build: ./web
    ports:
    - "8000:8000"
    links:
    - worker
  worker:
    build: ./worker
    env_file:
    - ./worker/.env.local
    ports:
    - "8200:8200"
  redis:
    image: "redis:alpine"
