version: '3'
services:
  web:
    build: ./web
    ports:
    - "80:80"
  worker:
    build: ./worker
    ports:
    - "8200:8200"
  backup:
    build: ./backup
  redis:
    image: "redis:alpine"
    ports:
    - "6379:6379"
